version: '3.7'
services:
  postgres:
    image: postgres:14
    hostname: ${POSTGRES_HOST}
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: "on-failure"
    networks:
      - banner-net

  banner:
    image: banner_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: "on-failure"
    networks:
      - banner-net

volumes:
  postgres_data:

networks:
  banner-net:
    driver: bridge
    name: banner-net
