env: development

server:
  host: localhost
  port: 8080
  user_token: "user"
  admin_token: "admin"

storage:
  migrations_path: ./migrations
  migration_table: versions
  pg_url: postgres://user:1234@localhost:5432/banner?sslmode=disable
